### ISSUE TITLE
Null en Panel de asistente

### ISSUE THREAD

**Issue by nunez7** [nunez7/sie#13]
## ¿Cómo puedo descubrir el problema?
Ir a panel de asistente, en el apartado de Grupos seleccionar uno que no tenga Profesor asignado (tutor) y saldrá el error en la vista.
## ¿En qué submódulo ocurre?
En 1/16

## ¿Desde que dispositivo estás accediendo?
Computadora 
## ¿Navegador web con el que estás accediendo?
Chrome

**Comment by Raul9901** [comment]
Se repara el error actualizando todos los grupos que no tengan un id_profesor a id_profesor = 1
