### ISSUE TITLE
Null en Panel de Director

### ISSUE THREAD

**Issue by nunez7** [nunez7/sie#14]
## ¿Cómo puedo descubrir el problema?
Entrar al Panel de Director con el rol de Administrador e ir a Fechas de entrega
## ¿En qué submódulo ocurre?
/2/2
## ¿Desde que dispositivo estás accediendo?
Computadora
## ¿Navegador web con el que estás accediendo?
Chrome

**Comment by Raul9901** [comment]
Se resuelve el error comparando que el director tenga asignadas carreras, si no tiene se le muestra un mensaje diciendo que no tiene carreras asignadas.
