### ISSUE TITLE
Reportes se deforman al dar clic en imprimir

### ISSUE THREAD

**Issue by nunez7** [nunez7/sie#15]
## ¿Cómo puedo descubrir el problema?
Ir a cualquier reporte que esté en Director y Asistente 
## ¿En qué submódulo ocurre?
Reportes de Director y Asistente
## ¿Desde que dispositivo estás accediendo?
Computadora
## ¿Navegador web con el que estás accediendo?
Chrome y Firefox

**Comment by Raul9901** [comment]
Se resuelve error cambiando el diseño del reporte y ajustando el estilo del mismo.
