### ISSUE TITLE
Reporte de asistencias muestra datos erróneos

### ISSUE THREAD

**Issue by ItsDonai** [nunez7/sie#35]
## ¿Cómo puedo descubrir el problema?
Por favor explica como replicar el problema y el momento en el que ocurre.
## ¿En qué submódulo ocurre?
Reportes de asistencias de profesor, director, asistente.

## ¿Desde que dispositivo estás accediendo?
Laptop

## ¿Navegador web con el que estás accediendo?
chrome

**Comment by Rhekhienth** [comment]
Se reestructuraron los reportes de asistencias de los módulos correspondientes
